apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: default
  labels:
    app: catalog
spec:
  clusterIP: None
  selector:
    app: catalog
  ports:
    - name: http
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: catalog
  namespace: default
spec:
  serviceName: catalog
  replicas: 2
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog-pod
          image: cloud-native-api-gateway-catalog-1:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
            - name: SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
